[package]
name = "shittyinput"
version = "1.0.0"
edition = "2021"
description = "An input library for rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/clear-leo/ShittyInput"

[dependencies]
